
import "./globals.css";


export const metadata = {
  title: "EmbaFit - Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        {children}
      </body>
    </html>
  );
}
