import Header from "@/components/header";
import Footer from "@/components/footer";
import WhatsAppButton from "@/components/whatsappButton";
import "../globals.css";


export const metadata = {
  title: "EmbaFit - Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <Header/>
        <WhatsAppButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
